[workspace]
members = [
    "demo",
    "mcaux-datalogger",
    "mcaux-indicators",
    "momentary",
]
resolver = "3"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 2

[patch.crates-io]
